version: "3"
services:
    back:
      build: 
        context: ./Back
        dockerfile: Dockerfile
      container_name: back-test-technique
      depends_on:
        - mongo
      ports:
       - "8800:8800"  
      restart: always
      networks:
        - test-technique_net
      environment: 
        - NODE_ENV=development
      volumes:
        - ./Back:/app/Back
        - '/app/Back/node_modules' 

    front:
      build: 
        context: ./Front
        dockerfile: Dockerfile
      container_name: front-test-technique
      ports:
       - '3001:3000'
      restart: always
      depends_on:
        - back
      networks:
        - test-technique_net     
      environment:
        - NODE_ENV=development    
      volumes:
        - ./Front/client:/app/Front/client
        - '/app/Front/client/node_modules'   

    mongo:
      image: mongo
      container_name: mongo-test-technique
      restart: always
      networks:
        - test-technique_net
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin
        MONGO_INITDB_DATABASE: test-technique
      volumes:
        - ./mongodb/datas/:/docker-entrypoint-initdb.d/

    mongo-express:
      image: mongo-express
      container_name: mongo-express-test-technique-dev
      ports:
        - 8081:8081
      restart: always
      networks:
        - test-technique_net
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        ME_CONFIG_MONGODB_ADMINPASSWORD: admin
networks:
  test-technique_net:
    driver: bridge